###################################################### CONFIGURE YOUR TOOLS HERE ######################################################

# >>>>>>>>>>> Global Settings <<<<<<<<<<<

# Directory and name of the files where history of applied jobs is saved (Sentence after the last "/" will be considered as the file name).
logs_folder_path: "logs/"

# Set the maximum amount of time allowed to wait between each click in secs
click_gap: 0                      # Enter max allowed secs to wait approximately. (Only Non Negative Integers Eg: 0,1,2,3,....)

# If you want to see Chrome running then set run_in_background as False (May reduce performance).
run_in_background: false          # true or false , If true, this will make pause_at_failed_question, pause_before_submit and run_in_background as False

# Run in safe mode. Set this true if chrome is taking too long to open or if you have multiple profiles in browser. This will open chrome in guest profile!
safe_mode: false                  # true or false

# Do you want scrolling to be smooth or instantaneous? (Can reduce performance if true)
smooth_scroll: false              # true or false

# If enabled (true), the program would keep your screen active and prevent PC from sleeping. Instead you could disable this feature (set it to false) and adjust your PC sleep settings to Never Sleep or a preferred time.
keep_screen_awake: true           # true or false (Note: Will temporarily deactivate when any application dialog boxes are present (Eg: Pause before submit, Help needed for a question..))

#<<<<<<<<<<<<< LinkedIn Settings >>>>>>>>>>>>>>>>
name: "Datta Lohith Gannavarapu"                 # Your Full Name

add_note: true                    # true or false

search_terms: ["Robotics Engineer","Computer vision Engineer","ML Engineer"] # List of search terms

max_connections_per_search: 11  # Maximum number of connections per search

